version: "3.9"

services:
  scraper:
    build: .
    container_name: fastapi_scraper
    ports:
      - "8000:8000"
    volumes:
      - ./saved_data:/app/saved_data
    env_file:
      - .env
    restart: always
